spring:
    datasource:
        url: ${db_url}
        username: ${db_username}
        password: ${db_password}
        driver-class-name: org.postgresql.Driver

    jpa:
        # database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
        show-sql: true
        database: postgresql

        hibernate:
            ddl-auto: update